// ══════════════════════════════════════════════════════════════
// InterviewHub AI — Roles & Badges Seed
// ══════════════════════════════════════════════════════════════

export const badgesSeed = [
  {
    name: "First Steps",
    slug: "first-steps",
    description: "Complete your first article",
    icon: "🎯",
    category: "learning",
    criteria: { type: "articles_read", threshold: 1 },
    xpReward: 10,
  },
  {
    name: "Bookworm",
    slug: "bookworm",
    description: "Read 50 articles",
    icon: "📚",
    category: "learning",
    criteria: { type: "articles_read", threshold: 50 },
    xpReward: 100,
  },
  {
    name: "Problem Solver",
    slug: "problem-solver",
    description: "Solve 10 coding problems",
    icon: "🧩",
    category: "coding",
    criteria: { type: "problems_solved", threshold: 10 },
    xpReward: 50,
  },
  {
    name: "Code Warrior",
    slug: "code-warrior",
    description: "Solve 100 coding problems",
    icon: "⚔️",
    category: "coding",
    criteria: { type: "problems_solved", threshold: 100 },
    xpReward: 500,
  },
  {
    name: "Community Star",
    slug: "community-star",
    description: "Get 50 upvotes on your posts",
    icon: "⭐",
    category: "community",
    criteria: { type: "upvotes_received", threshold: 50 },
    xpReward: 100,
  },
  {
    name: "Streak Master",
    slug: "streak-master",
    description: "Maintain a 30-day learning streak",
    icon: "🔥",
    category: "streak",
    criteria: { type: "streak_days", threshold: 30 },
    xpReward: 200,
  },
  {
    name: "Quiz Whiz",
    slug: "quiz-whiz",
    description: "Score 100% on 10 quizzes",
    icon: "🧠",
    category: "learning",
    criteria: { type: "perfect_quizzes", threshold: 10 },
    xpReward: 150,
  },
  {
    name: "Helping Hand",
    slug: "helping-hand",
    description: "Write 25 comments helping others",
    icon: "🤝",
    category: "community",
    criteria: { type: "comments_written", threshold: 25 },
    xpReward: 75,
  },
];

export const achievementsSeed = [
  {
    name: "Interview Ready",
    slug: "interview-ready",
    description: "Complete a full mock interview",
    icon: "🎤",
    tier: "bronze",
    criteria: { type: "mock_interviews", threshold: 1 },
    xpReward: 50,
  },
  {
    name: "Resume Pro",
    slug: "resume-pro",
    description: "Get an ATS score above 90",
    icon: "📄",
    tier: "silver",
    criteria: { type: "ats_score", threshold: 90 },
    xpReward: 100,
  },
  {
    name: "Full Stack Learner",
    slug: "full-stack-learner",
    description: "Study topics from all 7 categories",
    icon: "🏆",
    tier: "gold",
    criteria: { type: "categories_covered", threshold: 7 },
    xpReward: 300,
  },
  {
    name: "Contest Champion",
    slug: "contest-champion",
    description: "Win a coding contest",
    icon: "👑",
    tier: "platinum",
    criteria: { type: "contest_wins", threshold: 1 },
    xpReward: 500,
  },
];
